
# Data Exploration with Python

## Project Overview
This notebook demonstrates exploratory data analysis using the surveys dataset.

## Reading the dataset file

In [2]:

import pandas as pd
import numpy as np

surveys_df = pd.read_csv("data/surveys.csv")
surveys_df.head()

,record_id,month,day,year,plot_id,species_id,sex,hindfoot_length,weight
0,1,7,16,1977,2,NL,M,32.0,NaN
1,2,7,16,1977,3,NL,M,33.0,NaN
2,3,7,16,1977,2,DM,F,37.0,NaN
3,4,7,16,1977,7,DM,M,36.0,NaN
4,5,7,16,1977,3,DM,M,35.0,NaN

## Exploring the dataset

In [3]:

surveys_df.info()
surveys_df.dtypes

surveys_df.columns
surveys_df.shape
surveys_df.head(15)
surveys_df.tail()

pd.unique(surveys_df['species_id'])  #The pd.unique function tells us all of the unique values in the species_id column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35549 entries, 0 to 35548
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   record_id        35549 non-null  int64
 1   month            35549 non-null  int64
 2   day              35549 non-null  int64
 3   year             35549 non-null  int64
 4   plot_id          35549 non-null  int64
 5   species_id       34786 non-null  object
 6   sex              33038 non-null  object
 7   hindfoot_length  31438 non-null  float64
 8   weight           32283 non-null  float64
dtypes: float64(2), int64(5), object(2)
memory usage: 2.2+ MB

array(['NL', 'DM', 'PF', 'PE', 'DS', 'PP', 'SH', 'OT', 'DO', 'OX', 'SS',
       'OL', 'RM', nan, 'SA', 'PM', 'AH', 'DX', 'AB', 'CB', 'CM', 'CQ',
       'RF', 'PC', 'PG', 'PH', 'PU', 'CV', 'UR', 'UP', 'ZL', 'UL', 'CS',
       'SC', 'BA', 'SF', 'RO', 'AS', 'SO', 'PI', 'ST', 'CU', 'SU', 'RX',
       'PB', 'PL', 'PX', 'CT', 'US'], dtype=object)

## Calculating Summary Statistics

In [5]:

surveys_df['weight'].describe()
surveys_df['weight'].min()
surveys_df['weight'].max()
surveys_df['weight'].mean()
surveys_df['weight'].std()
surveys_df['weight'].count()

#Group data by sex
grouped_data = surveys_df.groupby('sex')  

#Summary statistics for all numeric columns by sex
grouped_data.describe() 

#Summary statistics for hinfoot_length column to grouped data by sex
grouped_data["hindfoot_length"].describe()  
#Grouping data by two columns instead of one
grouped_data2 = surveys_df.groupby(['plot_id', 'sex'])
grouped_data2.mean(numeric_only=True)
                  
#Specify particular columns and  summary statistics using the agg() method
surveys_df.groupby(['plot_id', 'sex']).agg({"year": 'max',
                                           "hindfoot_length": 'median',
                                           "weight": 'mean'})

             year  hindfoot_length     weight
plot_id sex
1       F    2002             34.0  46.311138
        M    2002             36.0  55.950560
2       F    2002             33.0  52.561845
        M    2002             33.0  51.391382
3       F    2002             22.0  31.215349
        M    2002             22.0  34.163241
4       F    2002             36.0  46.818824
        M    2002             36.0  48.888119
5       F    2002             34.0  40.974806
        M    2002             34.0  40.708551
6       F    2002             25.0  36.352288
        M    2002             25.0  36.867388
7       F    2002             20.0  20.006135
        M    2002             20.0  21.194719
8       F    2002             35.0  45.623011
        M    2002             36.0  49.641372
9       F    2002             36.0  53.618469
        M    2002             36.0  49.519309
10      F    2002             17.0  17.094203
        M    2002             17.0  19.971223
11      F    2002             35.0  43.515075
        M    2002             36.0  43.366197
12      F    2002             35.0  49.831731
        M    2002             35.0  48.909710
13      F    2002             25.0  40.524590
        M    2002             26.0  40.097754
14      F    2002             35.0  47.355491
        M    2002             36.0  45.159378
15      F    2002             21.0  26.670236
        M    2002             21.0  27.523691
16      F    2002             21.0  25.810427
        M    2002             21.0  23.811321
17      F    2002             34.0  48.176201
        M    2002             35.0  47.558853
18      F    2002             25.0  36.963514
        M    2002             26.0  43.546952
19      F    2002             21.0  21.978599
        M    2002             21.0  20.306878
20      F    2002             25.0  52.624406
        M    2002             26.0  44.197279
21      F    2002             24.0  25.974832
        M    2002             21.0  22.772622
22      F    2002             36.0  53.647059
        M    2002             36.0  54.572531
23      F    2002             18.0  20.564417
        M    2002             18.0  18.941463
24      F    2002             22.0  47.914405
        M    2002             21.0  39.321503

## Creating summary counts

In [6]:

#Count the number of samples by species
species_counts = surveys_df.groupby('species_id')['record_id'].count()

#Count the number of samples within the species “DO”
surveys_df.groupby('species_id')['record_id'].count()['DO']

np.int64(3027)

## Missing Values Assessment

In [7]:

#Count the number of missing values in each column 
for c in surveys_df.columns:
    print(c, len(surveys_df[surveys_df[c].isna()]))

#Drop all the rows that contain missing values
df_na = surveys_df.dropna()

record_id 0
month 0
day 0
year 0
plot_id 0
species_id 763
sex 2511
hindfoot_length 4111
weight 3266


## Key Points

- Pandas is a popular library for working with data.
- A Dataframe is a Pandas data structure that allows one to access data by column (name or index) or row.
- Aggregating data using the groupby() function enables you to generate useful summaries of data quickly.